apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cahl-orpheus-api-ingress
spec:
  tls:
  - secretName: orpheus-certchain
  rules:
  - host: api.cahl.orphe.us
    http:
      paths:
      - backend:
          serviceName: cahl-orpheus-api-service
          servicePort: 3001
